### PR TITLE
Fix blog link

### PR DESCRIPTION
**Pull request by midned**
Fixed your blog link.

I was also thinking about changing this line `(...)ranging from C# and Rust programming(...)` to `(...)ranging from C# and D programming(...)`

### CODE REVIEW

**Comment by midned** [comment]
Not that I want to tell you how to live your life

**Comment by dd86k** [comment]
how dare you tell me how to live

**Comment by dd86k** [comment]
Fixed with commit d1ac705 :)

**Comment by midned** [comment]
what about the 0evil link in my commit?

**Comment by dd86k** [comment]
oh oops fixing that too

**Comment by midned** [comment]
y u no merge my pull

**Comment by dd86k** [comment]
i trust myself thx

**Comment by midned** [comment]
at least follow me on the twittrz

**Comment by dd86k** [comment]
fineeeeee 

# e

**Pull request closed without merging**
